"""Initial migration

Revision ID: 3e9568179e56
Revises: fc6763cb6f4d
Create Date: 2024-05-22 22:48:38.847092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e9568179e56'
down_revision: Union[str, None] = 'fc6763cb6f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_booking_id', table_name='bookings')
    op.drop_index('ix_cashbacks_cashback_id', table_name='cashbacks')
    op.drop_index('ix_receipts_receipt_id', table_name='receipts')
    op.drop_index('ix_reviews_review_id', table_name='reviews')
    op.drop_index('ix_services_service_id', table_name='services')
    op.drop_index('ix_users_user_id', table_name='users')
    op.drop_index('ix_vendors_vendor_id', table_name='vendors')
    op.drop_index('ix_visits_visit_id', table_name='visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_visits_visit_id', 'visits', ['visit_id'], unique=False)
    op.create_index('ix_vendors_vendor_id', 'vendors', ['vendor_id'], unique=False)
    op.create_index('ix_users_user_id', 'users', ['user_id'], unique=False)
    op.create_index('ix_services_service_id', 'services', ['service_id'], unique=False)
    op.create_index('ix_reviews_review_id', 'reviews', ['review_id'], unique=False)
    op.create_index('ix_receipts_receipt_id', 'receipts', ['receipt_id'], unique=False)
    op.create_index('ix_cashbacks_cashback_id', 'cashbacks', ['cashback_id'], unique=False)
    op.create_index('ix_bookings_booking_id', 'bookings', ['booking_id'], unique=False)
    # ### end Alembic commands ###
