"""Initial migration

Revision ID: 74e586c9a7e0
Revises: 6b3f88a85184
Create Date: 2024-05-22 23:13:01.093839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e586c9a7e0'
down_revision: Union[str, None] = '6b3f88a85184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tg_username')
    # ### end Alembic commands ###
